import { Permission, Role } from '../types/auth.js';

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [Role.ADMIN]: Object.values(Permission),
  [Role.ACCOUNTANT]: [
    Permission.ACCOUNTS_CREATE,
    Permission.ACCOUNTS_READ,
    Permission.ACCOUNTS_UPDATE,
    Permission.JOURNAL_CREATE,
    Permission.JOURNAL_READ,
    Permission.JOURNAL_UPDATE,
    Permission.JOURNAL_SUBMIT,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.AUDIT_VIEW,
    Permission.COSO_VIEW,
    Permission.PIECES_VIEW,
  ],
  [Role.MANAGER]: [
    Permission.ACCOUNTS_READ,
    Permission.JOURNAL_READ,
    Permission.JOURNAL_POST,
    Permission.APPROVAL_VIEW,
    Permission.APPROVAL_DECIDE,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.AUDIT_VIEW,
    Permission.COSO_VIEW,
    Permission.COSO_EVALUATE,
    Permission.PIECES_VIEW,
    Permission.PIECES_MANAGE,
  ],
  [Role.AUDITOR]: [
    Permission.ACCOUNTS_READ,
    Permission.JOURNAL_READ,
    Permission.APPROVAL_VIEW,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.AUDIT_VIEW,
    Permission.AUDIT_VERIFY,
    Permission.COSO_VIEW,
    Permission.COSO_EVALUATE,
    Permission.PIECES_VIEW,
  ],
  [Role.VIEWER]: [
    Permission.ACCOUNTS_READ,
    Permission.JOURNAL_READ,
    Permission.REPORTS_VIEW,
    Permission.COSO_VIEW,
    Permission.PIECES_VIEW,
  ],
};
